export default {
    label: 'capitalize font-semibold flex items-end text-primary text-2xl max-md:w-min w-[200px]',
    span: 'font-caslon text-black font-normal text-lg',
    tableRow: 'flex flex-row justify-between w-full py-1 px-4 text-2xl font-normal',
    title: 'rounded-l-none rounded-r-none w-full hover:text-primary hover:underline hover:underline-offset-1',
    status: 'rounded-l-none rounded-r-none font-thin text-right',
    Aprobado: 'text-success',
    Denegado: 'text-error',
    Pendiente: 'text-black',
    mainContainer: 'mb-8 flex flex-row gap-8',
    leftContainer: 'flex flex-col justify-center items-center gap-[20px]',
    rightContainer: '',
    avatarCard: 'card text-gray-400 bg-secondary rounded-none h-[300px] w-[300px] flex flex-col justify-center items-center',
    tabs: '',
    tabItem: 'tab font-normal text-black text-2xl px-0 hover:text-primary',
    activeTab: 'tab font-normal text-2xl tab-active text-other px-0',
    editTab: 'text-other font-normal pr-0 tab text-2xl px-0 hover:text-primary',
    tabContent: 'border-none pb-4',
    btn: 'btn bg-other text-white hover:bg-primary btn-md rounded-full',
    fileInput: 'input hidden input-ghost w-full',
    fileLabel: 'label-text text-lg border-2 border-transparent py-2 rounded-none border-b-black',
    contProfile: 'overflow-hidden',
    contTabs: 'w-full ',
    contTabList: 'h-16',
    btnTitle: 'max-md:text-[11px] md:text-[15px] text-[#737373]'
}